// <auto-generated />
using ITDevProjekt.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITDevProjekt.Data.Migrations
{
    [DbContext(typeof(LangContext))]
    partial class LangContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ITDevProjekt.Data.Models.Langs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LangAttr");

                    b.Property<string>("LangName");

                    b.HasKey("Id");

                    b.ToTable("Langs");
                });
#pragma warning restore 612, 618
        }
    }
}
