// <auto-generated />
using ITDevProjekt.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ITDevProjekt.Data.Migrations
{
    [DbContext(typeof(ProjektDbContext))]
    partial class ProjektDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ITDevProjekt.Data.Models.Langs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LangAttr");

                    b.Property<string>("LangName");

                    b.HasKey("Id");

                    b.ToTable("Langs");
                });

            modelBuilder.Entity("ITDevProjekt.Data.Models.Translations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LangSource");

                    b.Property<string>("LangTranslate");

                    b.Property<string>("TextAfter");

                    b.Property<string>("TextBefore");

                    b.Property<string>("TextToken");

                    b.HasKey("Id");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
